packages:
  - .

allowBuilds:
  esbuild: true
  spawn-sync: true

minimumReleaseAgeExclude:
  - '@webext-core/fake-browser@2.0.1'
  - wxt@0.21.1

overrides:
  adm-zip: ^0.6.0
  brace-expansion: 5.0.8
  esbuild: ^0.28.1
  postcss: 8.5.23
  shell-quote: ^1.8.4
  tmp: ^0.2.6
  uuid: ^11.1.1
