import { z } from 'zod'
import type { BridgePayload } from './page-bridge'

export const BridgeEventSchema: z.ZodType<BridgePayload> = z.object({
  videoId: z.string().min(1),
  metadata: z.object({
    title: z.string(),
    author: z.string().optional(),
    durationMs: z.number().int().nonnegative().optional(),
  }),
  tracks: z.array(
    z.object({
      baseUrl: z.string().url(),
      languageCode: z.string().min(1),
      label: z.string(),
      vssId: z.string(),
      isAutoGenerated: z.boolean(),
    }),
  ),
})
