import { z } from 'zod'

export const BridgeEventSchema = z.object({
  videoId: z.string().min(1),
  metadata: z.object({
    title: z.string(),
    author: z.string().optional(),
    durationMs: z.number().int().nonnegative().optional(),
  }),
  tracks: z.array(
    z.object({
      baseUrl: z.string().url(),
      languageCode: z.string().min(1),
      label: z.string(),
      vssId: z.string(),
      isAutoGenerated: z.boolean(),
    }),
  ),
})

export type BridgePayload = z.infer<typeof BridgeEventSchema>

export const BRIDGE_EVENT_NAMES = {
  youtube: 'video-to-md:youtube-context',
  bilibili: 'video-to-md:bilibili-context',
} as const
