export const PAGE_BRIDGE_VERSION = 1

export interface BridgePayload {
  videoId: string
  metadata: {
    title: string
    author?: string
    durationMs?: number
  }
  tracks: Array<{
    baseUrl: string
    languageCode: string
    label: string
    vssId: string
    isAutoGenerated: boolean
  }>
}

export const YOUTUBE_CAPTION_BRIDGE = {
  requestEvent: 'video-to-md:youtube-caption-request',
  responseEvent: 'video-to-md:youtube-caption-response',
  requestAttribute: 'data-v2md-youtube-caption-request',
  responseAttribute: 'data-v2md-youtube-caption-response',
} as const
