import { AppError } from '../../errors/app-error'
import { CaptionTrackSchema } from './schemas'
import type { SubtitleAdapter, SubtitleTrack, SubtitleCue, VideoMetadata } from '../../core/contracts'
import type { BridgePayload } from '../shared/page-bridge'

const ALLOWED_CAPTION_HOSTS = new Set([
  'www.youtube.com',
  'youtube.com',
  'www.google.com',
])

export class YouTubeAdapter implements SubtitleAdapter {
  private readonly payload: BridgePayload
  private readonly fetchImpl: typeof fetch
  private readonly captionLoader?: (trackId: string) => Promise<Response>

  constructor(
    payload: BridgePayload,
    fetchImpl: typeof fetch = globalThis.fetch.bind(globalThis),
    captionLoader?: (trackId: string) => Promise<Response>,
  ) {
    this.payload = payload
    this.fetchImpl = fetchImpl
    this.captionLoader = captionLoader
  }

  supports(url: URL): boolean {
    return url.hostname === 'www.youtube.com' || url.hostname === 'youtube.com'
  }

  async getVideoMetadata(): Promise<VideoMetadata> {
    const { videoId, metadata } = this.payload
    return {
      platform: 'youtube',
      videoId,
      title: metadata.title,
      author: metadata.author,
      canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
      durationMs: metadata.durationMs,
    }
  }

  async getSubtitleTracks(): Promise<SubtitleTrack[]> {
    const { tracks } = this.payload
    if (tracks.length === 0) {
      throw new AppError('NO_SUBTITLE', '当前视频无可访问的字幕')
    }
    return tracks.map((t) => ({
      id: t.vssId,
      language: t.languageCode,
      label: t.label,
      isAutoGenerated: t.isAutoGenerated,
    }))
  }

  async getCues(track: SubtitleTrack): Promise<SubtitleCue[]> {
    const trackInfo = this.payload.tracks.find((t) => t.vssId === track.id)
    if (!trackInfo) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '未找到指定的字幕轨道')
    }

    // Validate HTTPS
    const parsedUrl = new URL(trackInfo.baseUrl)
    if (
      parsedUrl.protocol !== 'https:' ||
      (!ALLOWED_CAPTION_HOSTS.has(parsedUrl.hostname) &&
        !parsedUrl.hostname.endsWith('.googlevideo.com'))
    ) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕地址不在允许的 YouTube 域名内')
    }

    // Ensure fmt=json3 is set
    parsedUrl.searchParams.set('fmt', 'json3')

    let response: Response
    try {
      response = this.captionLoader
        ? await this.captionLoader(track.id)
        : await this.fetchImpl(parsedUrl.toString(), {
          credentials: 'include',
          headers: { Accept: 'application/json' },
        })
    } catch (e) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据获取失败: ${e instanceof Error ? e.message : '网络错误'}`,
      )
    }

    if (!response.ok) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕请求失败 (HTTP ${response.status})`,
      )
    }

    // Read as text first, then try JSON
    const rawText = await response.text().catch(() => '')
    if (rawText.trim().length === 0) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        'YouTube 返回了空字幕数据，请刷新视频页面后重试',
      )
    }
    if (rawText.trimStart().startsWith('<')) {
      return requireCaptionCues(parseXmlCaptions(rawText))
    }

    let body: unknown
    try {
      body = JSON.parse(rawText)
    } catch {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据格式异常，响应既不是 XML 也不是 JSON。响应预览: ${rawText.slice(0, 200)}`,
      )
    }

    const parsed = CaptionTrackSchema.safeParse(body)
    if (!parsed.success) {
      const keys = typeof body === 'object' && body !== null
        ? Object.keys(body as Record<string, unknown>).join(', ')
        : typeof body
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据结构不符合预期。返回字段: ${keys || '(空)'}`,
      )
    }

    const cues = parsed.data.events
      .map((event, index) => ({
        id: `yt-${index}`,
        startMs: event.tStartMs,
        endMs: event.tStartMs + event.dDurationMs,
        text: event.segs.map((seg) => seg.utf8).join(''),
      }))
      .filter((cue) => cue.text.trim().length > 0)
    return requireCaptionCues(cues)
  }
}

function requireCaptionCues(cues: SubtitleCue[]): SubtitleCue[] {
  if (cues.length === 0) {
    throw new AppError(
      'SUBTITLE_EXTRACTION_FAILED',
      'YouTube 字幕轨道没有可提取的文字内容，请切换字幕或刷新页面后重试',
    )
  }
  return cues
}

function parseXmlCaptions(rawText: string): SubtitleCue[] {
  const documentNode = new DOMParser().parseFromString(rawText, 'text/xml')
  if (documentNode.querySelector('parsererror')) {
    throw new AppError('SUBTITLE_EXTRACTION_FAILED', 'YouTube XML 字幕解析失败')
  }
  return [...documentNode.querySelectorAll('text')]
    .map((node, index) => {
      const startSeconds = Number(node.getAttribute('start') ?? '0')
      const durationSeconds = Number(node.getAttribute('dur') ?? '0')
      return {
        id: `yt-${index}`,
        startMs: Math.round(startSeconds * 1000),
        endMs: Math.round((startSeconds + durationSeconds) * 1000),
        text: node.textContent ?? '',
      }
    })
    .filter((cue) => cue.text.trim().length > 0)
}
