import { AppError } from '../../errors/app-error'
import { CaptionTrackSchema } from './schemas'
import type { SubtitleAdapter, SubtitleTrack, SubtitleCue, VideoMetadata } from '../../core/contracts'
import type { BridgePayload } from '../shared/page-bridge'

export class YouTubeAdapter implements SubtitleAdapter {
  private readonly payload: BridgePayload
  private readonly fetchImpl: typeof fetch

  constructor(payload: BridgePayload, fetchImpl: typeof fetch = globalThis.fetch.bind(globalThis)) {
    this.payload = payload
    this.fetchImpl = fetchImpl
  }

  supports(url: URL): boolean {
    return url.hostname === 'www.youtube.com' || url.hostname === 'youtube.com'
  }

  async getVideoMetadata(): Promise<VideoMetadata> {
    const { videoId, metadata } = this.payload
    return {
      platform: 'youtube',
      videoId,
      title: metadata.title,
      author: metadata.author,
      canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
      durationMs: metadata.durationMs,
    }
  }

  async getSubtitleTracks(): Promise<SubtitleTrack[]> {
    const { tracks } = this.payload
    if (tracks.length === 0) {
      throw new AppError('NO_SUBTITLE', '当前视频无可访问的字幕')
    }
    return tracks.map((t) => ({
      id: t.languageCode,
      language: t.languageCode,
      label: t.label,
      isAutoGenerated: t.isAutoGenerated,
    }))
  }

  async getCues(track: SubtitleTrack): Promise<SubtitleCue[]> {
    const trackInfo = this.payload.tracks.find((t) => t.languageCode === track.id)
    if (!trackInfo) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '未找到指定的字幕轨道')
    }

    // Validate HTTPS
    const parsedUrl = new URL(trackInfo.baseUrl)
    if (parsedUrl.protocol !== 'https:') {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕地址必须使用 HTTPS')
    }

    // Ensure fmt=json3 is set
    const baseUrl = trackInfo.baseUrl
    const sep = baseUrl.includes('?') ? '&' : '?'
    const fetchUrl = `${baseUrl}${sep}fmt=json3`

    let response: Response
    try {
      response = await this.fetchImpl(fetchUrl)
    } catch (e) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据获取失败: ${e instanceof Error ? e.message : '网络错误'}`,
      )
    }

    if (!response.ok) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕请求失败 (HTTP ${response.status})`,
      )
    }

    // Read as text first, then try JSON
    const rawText = await response.text().catch(() => '')
    let body: unknown
    try {
      body = JSON.parse(rawText)
    } catch {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据格式异常，服务器返回了非 JSON 数据。响应预览: ${rawText.slice(0, 200)}`,
      )
    }

    const parsed = CaptionTrackSchema.safeParse(body)
    if (!parsed.success) {
      const keys = typeof body === 'object' && body !== null
        ? Object.keys(body as Record<string, unknown>).join(', ')
        : typeof body
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据结构不符合预期。返回字段: ${keys || '(空)'}`,
      )
    }

    return parsed.data.events.map((event, index) => ({
      id: `yt-${index}`,
      startMs: event.tStartMs,
      endMs: event.tStartMs + event.dDurationMs,
      text: event.segs.map((seg) => seg.utf8).join(''),
    }))
  }
}
