import { AppError } from '../../errors/app-error'
import { CaptionTrackSchema } from './schemas'
import type { SubtitleAdapter, SubtitleTrack, SubtitleCue, VideoMetadata } from '../../core/contracts'
import type { BridgePayload } from '../shared/page-bridge'

export class YouTubeAdapter implements SubtitleAdapter {
  private readonly payload: BridgePayload
  private readonly fetchImpl: typeof fetch

  constructor(payload: BridgePayload, fetchImpl: typeof fetch = globalThis.fetch.bind(globalThis)) {
    this.payload = payload
    this.fetchImpl = fetchImpl
  }

  supports(url: URL): boolean {
    return url.hostname === 'www.youtube.com' || url.hostname === 'youtube.com'
  }

  async getVideoMetadata(): Promise<VideoMetadata> {
    const { videoId, metadata } = this.payload
    return {
      platform: 'youtube',
      videoId,
      title: metadata.title,
      author: metadata.author,
      canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
      durationMs: metadata.durationMs,
    }
  }

  async getSubtitleTracks(): Promise<SubtitleTrack[]> {
    const { tracks } = this.payload
    if (tracks.length === 0) {
      throw new AppError('NO_SUBTITLE', '当前视频无可访问的字幕')
    }
    return tracks.map((t) => ({
      id: t.languageCode,
      language: t.languageCode,
      label: t.label,
      isAutoGenerated: t.isAutoGenerated,
    }))
  }

  async getCues(track: SubtitleTrack): Promise<SubtitleCue[]> {
    const trackInfo = this.payload.tracks.find((t) => t.languageCode === track.id)
    if (!trackInfo) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '未找到指定的字幕轨道')
    }

    const url = new URL(trackInfo.baseUrl)
    if (url.protocol !== 'https:') {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕地址必须使用 HTTPS')
    }

    // Append fmt=json3 to get JSON3 format
    const fetchUrl = `${trackInfo.baseUrl}&fmt=json3`

    let response: Response
    try {
      response = await this.fetchImpl(fetchUrl)
    } catch {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕数据获取失败')
    }

    if (!response.ok) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', `字幕请求失败 (${response.status})`)
    }

    let body: unknown
    try {
      body = await response.json()
    } catch {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕数据格式异常')
    }

    const parsed = CaptionTrackSchema.safeParse(body)
    if (!parsed.success) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕数据结构不符合预期')
    }

    return parsed.data.events.map((event, index) => ({
      id: `yt-${index}`,
      startMs: event.tStartMs,
      endMs: event.tStartMs + event.dDurationMs,
      text: event.segs.map((seg) => seg.utf8).join(''),
    }))
  }
}
