import type { BridgePayload } from '../shared/page-bridge'
import { isOptionalString, isRecord } from '../shared/value-guards'

export function parseYouTubeInitialPlayerResponse(value: unknown): BridgePayload | null {
  if (!isRecord(value) || !isRecord(value.videoDetails)) return null

  const { videoDetails } = value
  if (
    typeof videoDetails.videoId !== 'string'
    || videoDetails.videoId.length === 0
    || typeof videoDetails.title !== 'string'
    || !isOptionalString(videoDetails.author)
    || !isOptionalString(videoDetails.lengthSeconds)
  ) {
    return null
  }

  const tracks = parseCaptionTracks(value.captions)
  if (tracks === null) return null

  return {
    videoId: videoDetails.videoId,
    metadata: {
      title: videoDetails.title,
      author: videoDetails.author,
      durationMs: parseDurationMs(videoDetails.lengthSeconds),
    },
    tracks,
  }
}

function parseCaptionTracks(value: unknown): BridgePayload['tracks'] | null {
  if (value === undefined) return []
  if (!isRecord(value) || !isRecord(value.playerCaptionsTracklistRenderer)) return null

  const { captionTracks } = value.playerCaptionsTracklistRenderer
  if (!Array.isArray(captionTracks)) return null

  const tracks: BridgePayload['tracks'] = []
  for (const candidate of captionTracks) {
    if (
      !isRecord(candidate)
      || typeof candidate.baseUrl !== 'string'
      || typeof candidate.languageCode !== 'string'
      || typeof candidate.vssId !== 'string'
      || !isOptionalString(candidate.kind)
      || !isRecord(candidate.name)
      || typeof candidate.name.simpleText !== 'string'
    ) {
      return null
    }
    tracks.push({
      baseUrl: candidate.baseUrl,
      languageCode: candidate.languageCode,
      label: candidate.name.simpleText,
      vssId: candidate.vssId,
      isAutoGenerated: candidate.kind === 'asr',
    })
  }
  return tracks
}

function parseDurationMs(value: string | undefined): number | undefined {
  if (value === undefined) return undefined
  const seconds = Number(value)
  if (!Number.isFinite(seconds) || seconds < 0) return undefined
  return Math.round(seconds * 1000)
}
