import { describe, expect, it, vi } from 'vitest'
import { BilibiliAdapter } from '../../src/adapters/bilibili/adapter'
import type { BilibiliContextPayload } from '../../src/adapters/bilibili/schemas'
import contextFixture from '../fixtures/bilibili/player-context.json'
import subtitlesFixture from '../fixtures/bilibili/player-subtitles.json'
import bodyFixture from '../fixtures/bilibili/subtitle-body.json'

const bridgePayload = contextFixture as BilibiliContextPayload

function createFetch() {
  return vi.fn().mockImplementation(async (input: RequestInfo | URL) => {
    const url = typeof input === 'string' ? input : input.toString()
    // Route: subtitle list API
    if (url.includes('/x/player/v2')) {
      return new Response(JSON.stringify(subtitlesFixture), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      })
    }
    // Route: subtitle body download
    if (url.includes('hdslb.com')) {
      return new Response(JSON.stringify(bodyFixture), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      })
    }
    return new Response('{}', { status: 404 })
  })
}

describe('BilibiliAdapter', () => {
  it('supports bilibili.com URLs', () => {
    const adapter = new BilibiliAdapter(bridgePayload, createFetch())
    expect(adapter.supports(new URL('https://www.bilibili.com/video/BV1xx411c7mD'))).toBe(true)
    expect(adapter.supports(new URL('https://www.youtube.com/watch?v=test123'))).toBe(false)
    expect(adapter.supports(new URL('https://bilibili.com/video/BV123'))).toBe(true)
  })

  it('returns video metadata', async () => {
    const adapter = new BilibiliAdapter(bridgePayload, createFetch())
    const metadata = await adapter.getVideoMetadata()

    expect(metadata).toMatchObject({
      platform: 'bilibili',
      videoId: 'BV1xx411c7mD',
      title: '人工智能入门教程',
      author: '科技频道',
      canonicalUrl: 'https://www.bilibili.com/video/BV1xx411c7mD',
      durationMs: 900000,
    })
  })

  it('maps Bilibili subtitle tracks to domain objects', async () => {
    const adapter = new BilibiliAdapter(bridgePayload, createFetch())
    const tracks = await adapter.getSubtitleTracks()

    expect(tracks).toEqual([
      {
        id: '12345',
        language: 'zh-CN',
        label: '中文（简体）',
        isAutoGenerated: false,
      },
      {
        id: '12346',
        language: 'en',
        label: '英语',
        isAutoGenerated: true,
      },
    ])
  })

  it('maps Bilibili subtitle seconds to milliseconds', async () => {
    const adapter = new BilibiliAdapter(bridgePayload, createFetch())
    const tracks = await adapter.getSubtitleTracks()

    const cues = await adapter.getCues(tracks[0]!)
    expect(cues).toHaveLength(3)
    expect(cues[0]).toEqual({
      id: 'bili-0',
      startMs: 1500,
      endMs: 3200,
      text: '欢迎来到测试视频。',
    })
    expect(cues[1]).toEqual({
      id: 'bili-1',
      startMs: 3500,
      endMs: 6000,
      text: '今天我们来讨论人工智能。',
    })
    expect(cues[2]).toEqual({
      id: 'bili-2',
      startMs: 6200,
      endMs: 9500,
      text: 'AI正在改变世界。',
    })
  })

  it('rejects a valid subtitle body without any text cues', async () => {
    const fetchImpl = vi.fn().mockImplementation(async (input: RequestInfo | URL) => {
      const url = input.toString()
      return new Response(JSON.stringify(
        url.includes('/x/player/v2') ? subtitlesFixture : { body: [] },
      ), { status: 200 })
    })
    const adapter = new BilibiliAdapter(bridgePayload, fetchImpl)
    const tracks = await adapter.getSubtitleTracks()

    await expect(adapter.getCues(tracks[0]!)).rejects.toThrow('没有可提取的文字内容')
  })

  it('throws NO_SUBTITLE when API returns empty list', async () => {
    const emptyFetch = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ code: 0, data: {} }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      }),
    )
    const adapter = new BilibiliAdapter(bridgePayload, emptyFetch)

    await expect(adapter.getSubtitleTracks()).rejects.toMatchObject({
      code: 'NO_SUBTITLE',
    })
  })

  it('rejects non-HTTPS subtitle URLs', async () => {
    const insecureSubs = {
      ...subtitlesFixture,
      data: {
        subtitle: {
          subtitles: [
            {
              id: 1,
              lan: 'zh-CN',
              lan_doc: '中文',
              subtitle_url: 'http://insecure.server/subtitle.json',
            },
          ],
        },
      },
    }
    const insecureFetch = vi.fn().mockResolvedValue(
      new Response(JSON.stringify(insecureSubs), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      }),
    )
    const adapter = new BilibiliAdapter(bridgePayload, insecureFetch)
    const tracks = await adapter.getSubtitleTracks()

    await expect(adapter.getCues(tracks[0]!)).rejects.toMatchObject({
      code: 'SUBTITLE_EXTRACTION_FAILED',
    })
  })

  it('accepts protocol-relative subtitle URLs from the Bilibili CDN', async () => {
    const relativeSubs = structuredClone(subtitlesFixture)
    relativeSubs.data.subtitle!.subtitles[0]!.subtitle_url =
      '//i0.hdslb.com/bfs/ai_subtitle/12345.json'
    const fetchImpl = vi.fn().mockImplementation(async (input: RequestInfo | URL) => {
      const url = input.toString()
      return new Response(JSON.stringify(
        url.includes('/x/player/v2') ? relativeSubs : bodyFixture,
      ), { status: 200 })
    })
    const adapter = new BilibiliAdapter(bridgePayload, fetchImpl)
    const tracks = await adapter.getSubtitleTracks()

    await expect(adapter.getCues(tracks[0]!)).resolves.toHaveLength(3)
    expect(fetchImpl).toHaveBeenLastCalledWith(
      'https://i0.hdslb.com/bfs/ai_subtitle/12345.json',
    )
  })
})
