import { describe, expect, it, vi } from 'vitest'
import { YouTubeAdapter } from '../../src/adapters/youtube/adapter'
import playerResponseFixture from '../fixtures/youtube/player-response.json'
import captionsFixture from '../fixtures/youtube/captions.json'

function createFetch() {
  return vi.fn().mockResolvedValue(
    new Response(JSON.stringify(captionsFixture), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    }),
  )
}

// Reconstruct the minimal bridge payload (what MAIN world extracts)
const bridgePayload = {
  videoId: playerResponseFixture.videoDetails.videoId,
  metadata: {
    title: playerResponseFixture.videoDetails.title,
    author: playerResponseFixture.videoDetails.author,
    durationMs:
      Number(playerResponseFixture.videoDetails.lengthSeconds) * 1000,
  },
  tracks:
    playerResponseFixture.captions.playerCaptionsTracklistRenderer.captionTracks.map(
      (t) => ({
        baseUrl: t.baseUrl,
        languageCode: t.languageCode,
        label: t.name.simpleText,
        vssId: t.vssId,
        isAutoGenerated: t.kind === 'asr',
      }),
    ),
}

describe('YouTubeAdapter', () => {
  it('supports youtube.com URLs', () => {
    const adapter = new YouTubeAdapter(bridgePayload, createFetch())
    expect(adapter.supports(new URL('https://www.youtube.com/watch?v=test123'))).toBe(true)
    expect(adapter.supports(new URL('https://www.bilibili.com/video/BV123'))).toBe(false)
    expect(adapter.supports(new URL('https://youtube.com/shorts/test123'))).toBe(true)
  })

  it('returns video metadata', async () => {
    const adapter = new YouTubeAdapter(bridgePayload, createFetch())
    const metadata = await adapter.getVideoMetadata()

    expect(metadata).toMatchObject({
      platform: 'youtube',
      videoId: 'test123',
      title: 'AI Agents Explained',
      author: 'Tech Channel',
      canonicalUrl: 'https://www.youtube.com/watch?v=test123',
      durationMs: 1_200_000,
    })
  })

  it('maps caption tracks to domain objects', async () => {
    const adapter = new YouTubeAdapter(bridgePayload, createFetch())
    const tracks = await adapter.getSubtitleTracks()

    expect(tracks).toEqual([
      {
        id: 'en',
        language: 'en',
        label: 'English',
        isAutoGenerated: false,
      },
      {
        id: 'zh-Hans',
        language: 'zh-Hans',
        label: '中文（简体）',
        isAutoGenerated: false,
      },
      {
        id: 'ja',
        language: 'ja',
        label: '日本語',
        isAutoGenerated: true,
      },
    ])
  })

  it('maps JSON3 events to subtitle cues', async () => {
    const adapter = new YouTubeAdapter(bridgePayload, createFetch())
    const cues = await adapter.getCues({
      id: 'en',
      language: 'en',
      label: 'English',
    })

    expect(cues).toHaveLength(3)
    expect(cues[0]).toEqual({
      id: 'yt-0',
      startMs: 1200,
      endMs: 2800,
      text: 'Welcome to the test.',
    })
    expect(cues[1]).toEqual({
      id: 'yt-1',
      startMs: 3000,
      endMs: 5000,
      text: 'Today we discuss artificial intelligence.',
    })
    expect(cues[2]).toEqual({
      id: 'yt-2',
      startMs: 5200,
      endMs: 7000,
      text: 'AI is transforming the world.',
    })
  })

  it('rejects non-HTTPS caption URLs', async () => {
    const insecurePayload = {
      ...bridgePayload,
      tracks: [
        { ...bridgePayload.tracks[0]!, baseUrl: 'http://evil.com/captions' },
      ],
    }
    const adapter = new YouTubeAdapter(insecurePayload, createFetch())

    await expect(
      adapter.getCues({ id: 'en', language: 'en', label: 'English' }),
    ).rejects.toMatchObject({ code: 'SUBTITLE_EXTRACTION_FAILED' })
  })

  it('throws NO_SUBTITLE for empty tracks', async () => {
    const emptyPayload = { ...bridgePayload, tracks: [] }
    const adapter = new YouTubeAdapter(emptyPayload, createFetch())

    await expect(adapter.getSubtitleTracks()).rejects.toMatchObject({
      code: 'NO_SUBTITLE',
    })
  })
})
