import type { VideoMetadata, SubtitleTrack } from '../core/contracts'

interface PrepareViewProps {
  metadata: VideoMetadata
  tracks: SubtitleTrack[]
  selectedTrackId: string
  mode: 'high-fidelity' | 'refined'
  includeTimestamps: boolean
  onTrackChange: (id: string) => void
  onModeChange: (mode: 'high-fidelity' | 'refined') => void
  onTimestampsChange: (v: boolean) => void
  onStart: () => void
}

export function PrepareView({
  metadata,
  tracks,
  selectedTrackId,
  mode,
  includeTimestamps,
  onTrackChange,
  onModeChange,
  onTimestampsChange,
  onStart,
}: PrepareViewProps) {
  return (
    <div>
      <h2>{metadata.title}</h2>
      <p>时长：{formatDuration(metadata.durationMs)}</p>

      <label htmlFor="track-select">字幕轨道</label>
      <select
        id="track-select"
        value={selectedTrackId}
        onChange={(e) => onTrackChange(e.target.value)}
      >
        {tracks.map((t) => (
          <option key={t.id} value={t.id}>
            {t.label}
            {t.isAutoGenerated ? ' (自动生成)' : ''}
          </option>
        ))}
      </select>

      <fieldset>
        <legend>处理模式</legend>
        <label>
          <input
            type="radio"
            name="mode"
            value="high-fidelity"
            checked={mode === 'high-fidelity'}
            onChange={() => onModeChange('high-fidelity')}
          />
          高保真
        </label>
        <label>
          <input
            type="radio"
            name="mode"
            value="refined"
            checked={mode === 'refined'}
            onChange={() => onModeChange('refined')}
          />
          AI 精炼
        </label>
      </fieldset>

      <label>
        <input
          type="checkbox"
          checked={includeTimestamps}
          onChange={(e) => onTimestampsChange(e.target.checked)}
        />
        保留时间戳
      </label>

      <button type="button" onClick={onStart}>
        开始生成
      </button>
    </div>
  )
}

function formatDuration(ms?: number): string {
  if (ms === undefined || ms === 0) return '--'
  const totalSeconds = Math.floor(ms / 1000)
  const m = Math.floor(totalSeconds / 60)
  const s = totalSeconds % 60
  return `${m}:${String(s).padStart(2, '0')}`
}
