export type Platform = 'youtube' | 'bilibili'

export type VideoMetadata = {
  platform: Platform
  videoId: string
  title: string
  author?: string
  canonicalUrl: string
  durationMs?: number
}

export type SubtitleTrack = {
  id: string
  language: string
  label: string
  isAutoGenerated?: boolean
}

export type SubtitleCue = {
  id: string
  startMs: number
  endMs: number
  text: string
}

export type VideoDocument = {
  metadata: VideoMetadata
  track: SubtitleTrack
  cues: SubtitleCue[]
}

export type ModelMessage = {
  role: 'system' | 'user'
  content: string
}

export type ModelRequest = {
  messages: ModelMessage[]
  responseFormat: 'json'
}

export type ModelResponse = {
  content: string
}

export type ModelActivity =
  | { type: 'connected' }
  | { type: 'delta'; text: string; receivedChars: number }

export type ModelCallContext = {
  taskId: string
  chunkIndex: number
  onActivity?: (activity: ModelActivity) => void
  onValidatedContent?: (content: unknown) => void
}

export interface SubtitleAdapter {
  supports(url: URL): boolean
  getVideoMetadata(): Promise<VideoMetadata>
  getSubtitleTracks(): Promise<SubtitleTrack[]>
  getCues(track: SubtitleTrack): Promise<SubtitleCue[]>
}

export interface ModelProvider {
  testConnection(signal?: AbortSignal): Promise<void>
  complete(
    request: ModelRequest,
    signal?: AbortSignal,
    context?: ModelCallContext,
  ): Promise<ModelResponse>
}
