import type { SubtitleTrack } from './contracts'

export type OutputLanguage = 'zh' | 'en'

const OUTPUT_LANGUAGE_LABELS: Record<OutputLanguage, string> = {
  zh: '中文',
  en: 'English',
}

export function languageFamily(language: string): string {
  return language.trim().toLowerCase().split(/[-_]/, 1)[0] ?? ''
}

export function isSameLanguage(left: string, right: string): boolean {
  return languageFamily(left) === languageFamily(right)
}

export function outputLanguageLabel(language: OutputLanguage): string {
  return OUTPUT_LANGUAGE_LABELS[language]
}

export function subtitleTrackLabel(track: SubtitleTrack): string {
  const autoSuffix = track.isAutoGenerated && !/(自动|auto)/i.test(track.label)
    ? '（自动生成）'
    : ''
  return `${track.label}${autoSuffix}`
}

export function preferredSubtitleTrack(
  tracks: SubtitleTrack[],
  outputLanguage: OutputLanguage,
): SubtitleTrack | undefined {
  const matching = tracks.filter(
    (track) => isSameLanguage(track.language, outputLanguage),
  )
  return matching.find((track) => !track.isAutoGenerated)
    ?? matching[0]
    ?? tracks.find((track) => !track.isAutoGenerated)
    ?? tracks[0]
}
