import { AppError } from '../../errors/app-error'
import { BilibiliSubtitleListSchema, BilibiliSubtitleBodySchema } from './schemas'
import type { BilibiliContextPayload } from './schemas'
import type { SubtitleAdapter, SubtitleTrack, SubtitleCue, VideoMetadata } from '../../core/contracts'

const PLAYER_API = 'https://api.bilibili.com/x/player/v2'
const ALLOWED_SUBTITLE_HOST_SUFFIX = '.hdslb.com'

type TrackInfo = {
  id: number
  lan: string
  lan_doc: string
  subtitle_url: string
  ai_status?: number
}

export class BilibiliAdapter implements SubtitleAdapter {
  private readonly context: BilibiliContextPayload
  private readonly fetchImpl: typeof fetch
  private trackList: TrackInfo[] | null = null

  constructor(
    context: BilibiliContextPayload,
    fetchImpl: typeof fetch = globalThis.fetch.bind(globalThis),
  ) {
    this.context = context
    this.fetchImpl = fetchImpl
  }

  supports(url: URL): boolean {
    return (
      url.hostname === 'www.bilibili.com' || url.hostname === 'bilibili.com'
    )
  }

  async getVideoMetadata(): Promise<VideoMetadata> {
    const { bvid, title, author, durationMs } = this.context
    return {
      platform: 'bilibili',
      videoId: bvid,
      title,
      author,
      canonicalUrl: `https://www.bilibili.com/video/${bvid}`,
      durationMs,
    }
  }

  async getSubtitleTracks(): Promise<SubtitleTrack[]> {
    const tracks = await this.fetchTrackList()
    if (tracks.length === 0) {
      throw new AppError('NO_SUBTITLE', '当前视频无可访问的字幕')
    }
    return tracks.map((t) => ({
      id: String(t.id),
      language: t.lan,
      label: t.lan_doc,
      isAutoGenerated: t.ai_status === 1,
    }))
  }

  async getCues(track: SubtitleTrack): Promise<SubtitleCue[]> {
    const tracks = await this.fetchTrackList()
    const trackInfo = tracks.find((t) => String(t.id) === track.id)
    if (!trackInfo) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '未找到指定的字幕轨道')
    }

    const url = new URL(trackInfo.subtitle_url, 'https://www.bilibili.com')
    if (
      url.protocol !== 'https:' ||
      !(url.hostname === 'hdslb.com' || url.hostname.endsWith(ALLOWED_SUBTITLE_HOST_SUFFIX))
    ) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕地址不在允许的 B 站域名内')
    }

    let response: Response
    try {
      response = await this.fetchImpl(url.toString())
    } catch {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕数据获取失败')
    }

    if (!response.ok) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕请求失败 (HTTP ${response.status})`,
      )
    }

    const rawText = await response.text().catch(() => '')
    let body: unknown
    try {
      body = JSON.parse(rawText)
    } catch {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕数据格式异常，服务器返回了非 JSON 数据。响应预览: ${rawText.slice(0, 200)}`,
      )
    }

    const parsed = BilibiliSubtitleBodySchema.safeParse(body)
    if (!parsed.success) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕数据结构不符合预期')
    }

    const cues = parsed.data.body
      .map((cue, index) => ({
        id: `bili-${index}`,
        startMs: Math.round(cue.from * 1000),
        endMs: Math.round(cue.to * 1000),
        text: cue.content,
      }))
      .filter((cue) => cue.text.trim().length > 0)
    if (cues.length === 0) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        'B 站字幕轨道没有可提取的文字内容，请切换字幕或刷新页面后重试',
      )
    }
    return cues
  }

  private async fetchTrackList(): Promise<TrackInfo[]> {
    if (this.trackList !== null) return this.trackList

    const url = `${PLAYER_API}?bvid=${this.context.bvid}&cid=${this.context.cid}`

    let response: Response
    try {
      response = await this.fetchImpl(url)
    } catch {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕列表获取失败')
    }

    if (!response.ok) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕列表请求失败 (${response.status})`,
      )
    }

    let body: unknown
    try {
      body = await response.json()
    } catch {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕列表格式异常')
    }

    const parsed = BilibiliSubtitleListSchema.safeParse(body)
    if (!parsed.success) {
      throw new AppError('SUBTITLE_EXTRACTION_FAILED', '字幕列表结构不符合预期')
    }
    if (parsed.data.code !== 0) {
      throw new AppError(
        'SUBTITLE_EXTRACTION_FAILED',
        `字幕列表接口返回错误 (${parsed.data.code})`,
      )
    }

    this.trackList = parsed.data.data.subtitle?.subtitles ?? []
    return this.trackList
  }
}
