import { YouTubeBridgePayloadSchema } from '../src/adapters/youtube/schemas'
import type { BridgePayload } from '../src/adapters/shared/page-bridge'

export default defineContentScript({
  matches: ['https://www.youtube.com/*'],
  world: 'MAIN',
  runAt: 'document_idle',
  main() {
    function extract() {
      const w = window as Window & {
        ytInitialPlayerResponse?: unknown
      }
      const raw = w.ytInitialPlayerResponse
      if (!raw) return

      const parsed = YouTubeBridgePayloadSchema.safeParse(raw)
      if (!parsed.success) return

      const { videoDetails, captions } = parsed.data

      const payload: BridgePayload = {
        videoId: videoDetails.videoId,
        metadata: {
          title: videoDetails.title,
          author: videoDetails.author,
          durationMs: videoDetails.lengthSeconds
            ? Number(videoDetails.lengthSeconds) * 1000
            : undefined,
        },
        tracks:
          captions?.playerCaptionsTracklistRenderer.captionTracks.map((t) => ({
            baseUrl: t.baseUrl,
            languageCode: t.languageCode,
            label: t.name.simpleText,
            vssId: t.vssId,
            isAutoGenerated: t.kind === 'asr',
          })) ?? [],
      }

      // Write to DOM so ISOLATED world can always read it
      document.documentElement.setAttribute(
        'data-v2md-youtube',
        JSON.stringify(payload),
      )
    }

    // Try immediately
    extract()

    // Also watch for SPA navigation (YouTube is a SPA)
    const observer = new MutationObserver(() => extract())
    observer.observe(document.title ? document.head : document.documentElement, {
      childList: true,
      subtree: true,
    })

    // Clean up observer after 60s to avoid leaks
    setTimeout(() => observer.disconnect(), 60_000)
  },
})
