import { YouTubeBridgePayloadSchema } from '../src/adapters/youtube/schemas'
import type { BridgePayload } from '../src/adapters/shared/page-bridge'

export default defineContentScript({
  matches: ['https://www.youtube.com/*'],
  world: 'MAIN',
  runAt: 'document_idle',
  main() {
    const w = window as Window & {
      ytInitialPlayerResponse?: unknown
    }

    const raw = w.ytInitialPlayerResponse
    if (!raw) return

    const parsed = YouTubeBridgePayloadSchema.safeParse(raw)
    if (!parsed.success) return

    const { videoDetails, captions } = parsed.data

    const payload: BridgePayload = {
      videoId: videoDetails.videoId,
      metadata: {
        title: videoDetails.title,
        author: videoDetails.author,
        durationMs: videoDetails.lengthSeconds
          ? Number(videoDetails.lengthSeconds) * 1000
          : undefined,
      },
      tracks:
        captions?.playerCaptionsTracklistRenderer.captionTracks.map((t) => ({
          baseUrl: t.baseUrl,
          languageCode: t.languageCode,
          label: t.name.simpleText,
          vssId: t.vssId,
          isAutoGenerated: t.kind === 'asr',
        })) ?? [],
    }

    window.dispatchEvent(
      new CustomEvent('video-to-md:youtube-context', {
        detail: payload,
      }),
    )
  },
})
