import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { App } from '../../src/components/App'
import { AppShell } from '../../src/components/layout/AppShell'
import { AppHeader } from '../../src/components/layout/AppHeader'
import { BottomActionBar } from '../../src/components/layout/BottomActionBar'
import { Button } from '../../src/components/ui/Button'
import { PAGE_BRIDGE_VERSION } from '../../src/adapters/shared/page-bridge'

describe('side panel shell', () => {
  afterEach(() => vi.restoreAllMocks())

  it('keeps the footer outside the scrollable content so it cannot cover content', () => {
    const { container } = render(
      <AppShell
        header={<AppHeader />}
        footer={<BottomActionBar><Button variant="primary">继续</Button></BottomActionBar>}
      >
        <p>长内容</p>
      </AppShell>,
    )

    const content = container.querySelector('.app-shell__content')
    const footer = container.querySelector('.app-shell__footer')
    expect(content).toHaveClass('app-shell__content--with-footer')
    expect(footer).not.toBeNull()
    expect(content?.contains(footer)).toBe(false)
    expect(within(footer as HTMLElement).getByRole('button', { name: '继续' })).toBeVisible()
  })

  it('shows the product name', async () => {
    vi.spyOn(
      chrome.tabs as unknown as { query: () => Promise<chrome.tabs.Tab[]> },
      'query',
    ).mockResolvedValue([{
      id: 4,
      url: 'https://example.com/',
    } as chrome.tabs.Tab])
    render(<App />)

    expect(screen.getByRole('heading', { name: 'Video to Markdown' })).toBeVisible()
    expect(await screen.findByRole('heading', { name: '打开一个视频开始' })).toBeVisible()
  })

  it('detects the page without forcing model configuration and restores home after settings', async () => {
    vi.spyOn(
      chrome.tabs as unknown as { query: () => Promise<chrome.tabs.Tab[]> },
      'query',
    ).mockResolvedValue([{
      id: 5,
      url: 'https://example.com/',
    } as chrome.tabs.Tab])
    const user = userEvent.setup()
    render(<App />)

    expect(await screen.findByRole('heading', { name: '打开一个视频开始' })).toBeVisible()
    await user.click(screen.getByRole('button', { name: '模型设置' }))
    expect(screen.getByLabelText('API Key')).toBeVisible()

    await user.click(screen.getByRole('button', { name: '返回' }))
    expect(screen.getByRole('heading', { name: '打开一个视频开始' })).toBeVisible()
  })

  it('returns to the same English video after saving and testing a required model', async () => {
    vi.spyOn(
      chrome.storage.local as unknown as {
        get: (keys: string[]) => Promise<Record<string, unknown>>
      },
      'get',
    ).mockImplementation(async (keys) => {
      if (keys.includes('userPreferences')) {
        return {
          userPreferences: {
            selectedTrackId: '.en',
            mode: 'high-fidelity',
            includeTimestamps: true,
            outputLanguage: 'zh',
            lastProviderId: 'deepseek',
          },
        }
      }
      return {}
    })
    const storageSet = vi.spyOn(
      chrome.storage.local as unknown as {
        set: (items: Record<string, unknown>) => Promise<void>
      },
      'set',
    ).mockResolvedValue(undefined)
    vi.spyOn(
      chrome.tabs as unknown as { query: () => Promise<chrome.tabs.Tab[]> },
      'query',
    ).mockResolvedValue([{
      id: 12,
      url: 'https://www.youtube.com/watch?v=english-video',
    } as chrome.tabs.Tab])
    vi.spyOn(
      chrome.tabs as unknown as { sendMessage: () => Promise<unknown> },
      'sendMessage',
    ).mockResolvedValue({
      success: true,
      bridgeVersion: PAGE_BRIDGE_VERSION,
      platform: 'youtube',
      data: {
        videoId: 'english-video',
        metadata: { title: 'English Video', author: 'Author', durationMs: 60_000 },
        tracks: [{
          baseUrl: 'https://www.youtube.com/api/timedtext?v=english-video&lang=en',
          languageCode: 'en',
          label: 'English',
          vssId: '.en',
          isAutoGenerated: false,
        }],
      },
    })
    const runtimeSend = vi.spyOn(
      chrome.runtime as unknown as { sendMessage: () => Promise<unknown> },
      'sendMessage',
    ).mockResolvedValue({ success: true, data: { ok: true } })
    const permissionsRequest = vi.spyOn(
      chrome.permissions as unknown as {
        request: (permissions: { origins: string[] }) => Promise<boolean>
      },
      'request',
    ).mockResolvedValue(true)

    const user = userEvent.setup()
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'English Video' })).toBeVisible()
    expect(screen.getByRole('button', { name: '配置模型并继续' })).toBeVisible()
    expect(screen.getByLabelText('保留时间戳')).toBeChecked()

    await user.click(screen.getByRole('button', { name: '配置模型并继续' }))
    await user.type(screen.getByLabelText('API Key'), 'sk-deepseek-test')
    await user.click(screen.getByRole('button', { name: '保存并测试' }))

    await waitFor(() => expect(permissionsRequest).toHaveBeenCalledWith({
      origins: ['https://api.deepseek.com/*'],
    }))
    expect(storageSet).toHaveBeenCalled()
    expect(runtimeSend).toHaveBeenCalledWith({ type: 'MODEL_TEST_REQUEST' })
    expect(await screen.findByText('连接成功')).toBeVisible()
    await user.click(screen.getByRole('button', { name: '返回视频继续' }))
    expect(screen.getByRole('heading', { name: 'English Video' })).toBeVisible()
    expect(screen.getByRole('combobox', { name: '字幕来源' })).toHaveValue('.en')
    expect(screen.getByRole('radio', { name: '中文' })).toBeChecked()
    expect(screen.getByLabelText('保留时间戳')).toBeChecked()
    expect(screen.getByRole('button', { name: '开始生成' })).toBeVisible()
  })
})
