import { describe, expect, it } from 'vitest'
import {
  isSameLanguage,
  preferredSubtitleTrack,
  subtitleTrackLabel,
} from '../../src/core/language'
import type { SubtitleTrack } from '../../src/core/contracts'

const tracks: SubtitleTrack[] = [
  { id: 'en-auto', language: 'en', label: 'English', isAutoGenerated: true },
  { id: 'zh-human', language: 'zh-Hans', label: '中文（简体）' },
  { id: 'en-human', language: 'en-US', label: 'English (US)' },
]

describe('language selection', () => {
  it('treats regional variants as the same output language', () => {
    expect(isSameLanguage('zh-Hans', 'zh')).toBe(true)
    expect(isSameLanguage('en-US', 'en')).toBe(true)
    expect(isSameLanguage('en', 'zh')).toBe(false)
  })

  it('prefers a human track matching the requested output language', () => {
    expect(preferredSubtitleTrack(tracks, 'zh')?.id).toBe('zh-human')
    expect(preferredSubtitleTrack(tracks, 'en')?.id).toBe('en-human')
  })

  it('does not duplicate an existing auto-generated label', () => {
    expect(subtitleTrackLabel({
      id: 'auto',
      language: 'en',
      label: '英语（自动生成）',
      isAutoGenerated: true,
    })).toBe('英语（自动生成）')
    expect(subtitleTrackLabel(tracks[0]!)).toBe('English（自动生成）')
  })
})
