import { describe, expect, it } from 'vitest'
import { parseBilibiliMainWorldContext } from '../../src/adapters/bilibili/main-world-parser'
import { parseYouTubeInitialPlayerResponse } from '../../src/adapters/youtube/main-world-parser'
import youtubePlayerResponse from '../fixtures/youtube/player-response.json'

describe('MAIN world parsers', () => {
  it('extracts the minimal YouTube bridge payload without a runtime schema library', () => {
    const payload = parseYouTubeInitialPlayerResponse(youtubePlayerResponse)

    expect(payload).toMatchObject({
      videoId: 'test123',
      metadata: {
        title: 'AI Agents Explained',
        author: 'Tech Channel',
        durationMs: 1_200_000,
      },
    })
    expect(payload?.tracks).toHaveLength(3)
    expect(payload?.tracks[0]).toMatchObject({
      languageCode: 'en',
      label: 'English',
      vssId: '.en',
      isAutoGenerated: false,
    })
  })

  it('rejects malformed YouTube caption tracks', () => {
    expect(parseYouTubeInitialPlayerResponse({
      videoDetails: {
        videoId: 'video-id',
        title: 'Video',
      },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [{ baseUrl: 'https://www.youtube.com/api/timedtext' }],
        },
      },
    })).toBeNull()
  })

  it('accepts a valid Bilibili page context', () => {
    expect(parseBilibiliMainWorldContext({
      bvid: 'BV1xx411c7mD',
      aid: 1,
      cid: 2,
      title: '测试视频',
      author: '测试作者',
      durationMs: 120_000,
    })).toEqual({
      bvid: 'BV1xx411c7mD',
      aid: 1,
      cid: 2,
      title: '测试视频',
      author: '测试作者',
      durationMs: 120_000,
    })
  })

  it('rejects an invalid Bilibili page context', () => {
    expect(parseBilibiliMainWorldContext({
      bvid: 'BV1xx411c7mD',
      aid: 1,
      cid: -1,
      title: '测试视频',
    })).toBeNull()
  })
})
