import { describe, expect, it, vi } from 'vitest'
import {
  activeTabIdentity,
  classifyVideoUrl,
  getActiveTabSnapshot,
  reloadTabAndWait,
  shouldConfirmTabSwitch,
  type ActiveTabSnapshot,
  type ReloadTabDeps,
} from '../../src/browser/active-tab'
import { mapVideoContextError, requestVideoContext } from '../../src/browser/video-context'
import { AppError } from '../../src/errors/app-error'
import { PAGE_BRIDGE_VERSION } from '../../src/adapters/shared/page-bridge'

const youtubeTab: ActiveTabSnapshot = {
  tabId: 7,
  url: 'https://www.youtube.com/watch?v=video-1&t=10',
  video: { platform: 'youtube', videoId: 'video-1' },
}

const youtubePayload = {
  videoId: 'video-1',
  metadata: { title: '测试视频', author: '作者', durationMs: 60_000 },
  tracks: [{
    baseUrl: 'https://www.youtube.com/api/timedtext?v=video-1&lang=zh',
    languageCode: 'zh',
    label: '中文',
    vssId: '.zh',
    isAutoGenerated: false,
  }],
}

describe('active video tab', () => {
  it('classifies supported URLs without accepting lookalike domains', () => {
    expect(classifyVideoUrl('https://www.youtube.com/watch?v=abc')).toEqual({
      platform: 'youtube',
      videoId: 'abc',
    })
    expect(classifyVideoUrl('https://www.bilibili.com/video/BV1xx411c7mD?p=2')).toEqual({
      platform: 'bilibili',
      videoId: 'BV1xx411c7mD',
    })
    expect(classifyVideoUrl('https://youtube.com.evil.test/watch?v=abc')).toBeNull()
    expect(classifyVideoUrl('https://www.youtube.com/')).toBeNull()
  })

  it('queries and normalizes the active tab', async () => {
    const query = vi.fn().mockResolvedValue([{ id: 7, url: youtubeTab.url }])
    await expect(getActiveTabSnapshot(query)).resolves.toEqual(youtubeTab)
    expect(query).toHaveBeenCalledWith({ active: true, currentWindow: true })
  })

  it('uses tab and video identity to decide whether a task needs confirmation', () => {
    const next = {
      tabId: 8,
      url: 'https://www.bilibili.com/video/BV123',
      video: { platform: 'bilibili', videoId: 'BV123' },
    } satisfies ActiveTabSnapshot
    expect(activeTabIdentity(youtubeTab)).toBe('7:youtube:video-1')
    expect(shouldConfirmTabSwitch(youtubeTab, next, true)).toBe(true)
    expect(shouldConfirmTabSwitch(youtubeTab, next, false)).toBe(false)
    expect(shouldConfirmTabSwitch(youtubeTab, youtubeTab, true)).toBe(false)
  })
})

describe('versioned video context handshake', () => {
  it('returns a validated YouTube context', async () => {
    const sendMessage = vi.fn().mockResolvedValue({
      success: true,
      bridgeVersion: PAGE_BRIDGE_VERSION,
      platform: 'youtube',
      data: youtubePayload,
    })

    await expect(requestVideoContext(youtubeTab, { sendMessage })).resolves.toEqual({
      platform: 'youtube',
      data: youtubePayload,
    })
  })

  it('waits for context matching the active YouTube video after SPA navigation', async () => {
    const sendMessage = vi.fn()
      .mockResolvedValueOnce({
        success: true,
        bridgeVersion: PAGE_BRIDGE_VERSION,
        platform: 'youtube',
        data: { ...youtubePayload, videoId: 'previous-video' },
      })
      .mockResolvedValueOnce({
        success: true,
        bridgeVersion: PAGE_BRIDGE_VERSION,
        platform: 'youtube',
        data: youtubePayload,
      })
    const sleep = vi.fn().mockResolvedValue(undefined)

    await expect(requestVideoContext(youtubeTab, {
      attempts: 2,
      retryDelayMs: 0,
      sendMessage,
      sleep,
    })).resolves.toEqual({ platform: 'youtube', data: youtubePayload })
    expect(sendMessage).toHaveBeenCalledTimes(2)
    expect(sleep).toHaveBeenCalledOnce()
  })

  it('never accepts a Bilibili context belonging to another video', async () => {
    const bilibiliTab: ActiveTabSnapshot = {
      tabId: 8,
      url: 'https://www.bilibili.com/video/BV-current',
      video: { platform: 'bilibili', videoId: 'BV-current' },
    }
    const staleContext = {
      bvid: 'BV-previous',
      aid: 1,
      cid: 2,
      title: '旧视频',
    }

    const error = await requestVideoContext(bilibiliTab, {
      attempts: 2,
      retryDelayMs: 0,
      sendMessage: vi.fn().mockResolvedValue({
        success: true,
        bridgeVersion: PAGE_BRIDGE_VERSION,
        platform: 'bilibili',
        data: staleContext,
      }),
      sleep: vi.fn().mockResolvedValue(undefined),
    }).catch((reason: unknown) => reason)

    expect(error).toMatchObject({ code: 'CONTENT_SCRIPT_UNAVAILABLE' })
  })

  it('maps a missing content script to refresh-required without reading error text', async () => {
    const error = await requestVideoContext(youtubeTab, {
      attempts: 2,
      retryDelayMs: 0,
      sendMessage: vi.fn().mockRejectedValue(new Error('Receiving end does not exist')),
      sleep: vi.fn().mockResolvedValue(undefined),
    }).catch((reason: unknown) => reason)

    expect(error).toMatchObject({ code: 'CONTENT_SCRIPT_UNAVAILABLE' })
    expect(mapVideoContextError(error, { tabId: youtubeTab.tabId })).toEqual({
      status: 'refresh-required',
      tabId: youtubeTab.tabId,
    })
  })

  it('also treats an empty message response as a missing content script', async () => {
    const error = await requestVideoContext(youtubeTab, {
      attempts: 1,
      sendMessage: vi.fn().mockResolvedValue(undefined),
    }).catch((reason: unknown) => reason)

    expect(error).toMatchObject({ code: 'CONTENT_SCRIPT_UNAVAILABLE' })
  })

  it('treats malformed versioned context as a platform error', async () => {
    const error = await requestVideoContext(youtubeTab, {
      sendMessage: vi.fn().mockResolvedValue({
        success: true,
        bridgeVersion: PAGE_BRIDGE_VERSION,
        platform: 'youtube',
        data: { videoId: 'video-1', tracks: 'invalid' },
      }),
    }).catch((reason: unknown) => reason)

    expect(error).toMatchObject({ code: 'PAGE_CONTEXT_INVALID' })
    expect(mapVideoContextError(error, { tabId: youtubeTab.tabId })).toMatchObject({
      status: 'failed',
      error: { code: 'PAGE_CONTEXT_INVALID' },
    })
  })

  it('maps NO_SUBTITLE separately from subtitle API failures', () => {
    const metadata = {
      platform: 'youtube' as const,
      videoId: 'video-1',
      title: '测试视频',
      canonicalUrl: youtubeTab.url,
    }
    expect(mapVideoContextError(
      new AppError('NO_SUBTITLE', '无字幕'),
      { tabId: youtubeTab.tabId, metadata },
    )).toEqual({ status: 'no-subtitle', metadata })

    expect(mapVideoContextError(
      new AppError('SUBTITLE_EXTRACTION_FAILED', '接口失败'),
      { tabId: youtubeTab.tabId, metadata },
    )).toMatchObject({
      status: 'failed',
      error: { code: 'SUBTITLE_EXTRACTION_FAILED' },
    })
  })
})

describe('tab reload', () => {
  it('waits for the target tab to finish loading', async () => {
    let listener: Parameters<ReloadTabDeps['addUpdatedListener']>[0] | undefined
    const deps: ReloadTabDeps = {
      addUpdatedListener: (nextListener) => { listener = nextListener },
      removeUpdatedListener: vi.fn(),
      reload: vi.fn().mockImplementation(async () => {
        listener?.(7, { status: 'complete' }, {} as chrome.tabs.Tab)
      }),
      timeoutMs: 100,
    }

    await expect(reloadTabAndWait(7, deps)).resolves.toBeUndefined()
    expect(deps.reload).toHaveBeenCalledWith(7)
    expect(deps.removeUpdatedListener).toHaveBeenCalledOnce()
  })
})
